freebsd_task:
  freebsd_instance:
    image_family: freebsd-12-2
  clone_script:
    - sed -i.bak -e 's,/quarterly,/latest,' /etc/pkg/FreeBSD.conf
    - pkg install -y git-lite
    - git clone --recurse-submodules --branch=$CIRRUS_BRANCH https://github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
  cppcheck_script:
    - pkg install -y cppcheck
  matrix:
    - name: freebsd_clang
    - name: freebsd_gcc
      gcc_script: pkg install -y gcc
      env:
        CC: gcc
  test_script:
    - ./configure
    - make test

linux_task:
  container:
    image: gcc:latest
  clone_script:
    - git clone --recurse-submodules --branch=$CIRRUS_BRANCH https://github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
  deps_script:
    - apt-get update && apt-get -y install bash cppcheck mandoc
  matrix:
    - name: linux_clang
      env:
        CC: clang
      clang_script:
        - apt-get -y install clang
    - name: linux_gcc
  test_script:
    - ./configure
# for -o pipefail
    - make SH=bash test

macos_task:
  osx_instance:
    image: catalina-base
  matrix:
    - name: macos_clang
      env:
        CC: clang
    - name: macos_gcc
  clone_script:
    - git clone --recurse-submodules --branch=$CIRRUS_BRANCH https://github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
  test_script:
    - ./configure
    - make test
