#!/bin/sh
#
# Copyright (c) 2019, Tobias Kortkamp <tobik@FreeBSD.org>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY ``AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN
# NO EVENT SHALL I BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# MAINTAINER=	tobik@FreeBSD.org
#
set -eu

usage() {
	echo "usage: portfmt [-i] [-w wrapcol] [Makefile]" 1>&2
	return 64
}

main() {
	if ! command -v portfmt.awk >/dev/null; then
		echo "portfmt: portfmt.awk: not found" 1>&2
		exit 1
	fi

	while getopts "iw:" arg; do
		case ${arg} in
		i) export INPLACE=1 ;;
		w) export WRAPCOL="${OPTARG}" ;;
		*) usage ;;
		esac
	done
	shift $((OPTIND - 1))

	if [ $# -gt 1 ]; then
		usage
	fi

	exec portfmt.awk "$@"
}

main "$@"
