.\"-
.\" SPDX-License-Identifier: BSD-2-Clause-FreeBSD
.\"
.\" Copyright (c) 2019 Tobias Kortkamp <tobik@FreeBSD.org>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd November 9, 2019
.Dt PORTFMT 1
.Os
.Sh NAME
.Nm portfmt
.Nd "format FreeBSD Ports Collection Makefiles"
.Sh SYNOPSIS
.Nm
.Op Fl ditu
.Op Fl w Ar wrapcol
.Op Ar Makefile
.Sh DESCRIPTION
.Nm
is a tool for formatting
.Fx
Ports Collection Makefiles.
.Pp
If the optional
.Ar Makefile
argument is not given, the Makefile will be read from stdin.
This can be useful for editor integration where you might want to
only format portions of your Makefile.
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl d
Dump the list of recognized tokens to stdout.
This is only useful for debugging purposes.
If this flag is specified
.Fl i
is ignored.
.It Fl i
Format
.Ar Makefile
in-place instead of writing the result to stdout.
.It Fl t
Format and reindent target commands.
.It Fl u
Leave variables unsorted.
.It Fl w Ar wrapcol
Sets the wrapping column to
.Ar wrapcol
(default: 80).
This is a goal not a hard value.
It will be ignored for several variables like COMMENT, DISTFILES,
MASTER_SITES, etc.
.Pp
With a value of -1 it is ignored for all variables.
Variables with wrapped tokens over multiple lines will be concatenated
onto a single line.
.El
.Sh EDITOR INTEGRATION
You can integrate Portfmt into your editor to conveniently run it
only on parts of the port, e.g., to reformat USES after adding a
new item to it.
.Ss Emacs
Add this to
.Pa ~/.emacs.d/init.el
to format the current region with
.Sy C-c p :
.Bd -literal -offset indent
(defun portfmt (&optional b e)
  "PORTFMT(1) on region"
  (interactive "r")
  (shell-command-on-region b e "portfmt " (current-buffer) t
                           "*portfmt errors*" t))
.Ed
.Bd -literal -offset indent
(define-key makefile-bsdmake-mode-map (kbd "C-c p") 'portfmt)
.Ed
.Ss Kakoune
Add this to
.Pa ~/.config/kak/kakrc
for filtering the current selection through
.Nm
with
.Sy ,1 :
.Bd -literal -offset indent
map global user 1 '|portfmt<ret>;' \\
	-docstring "portfmt on selection"
.Ed
.Ss Vim
Add this to
.Pa ~/.vimrc
for filtering the current selection through
.Nm
with
.Sy \e1 :
.Bd -literal -offset indent
xnoremap <leader>1 <esc>:'<,'>!portfmt<CR>
.Ed
.Sh EXAMPLES
In-place format
.Pa /usr/ports/audio/sndio/Makefile :
.Bd -literal -offset indent
portfmt -i /usr/ports/audio/sndio/Makefile
.Ed
.Sh SEE ALSO
.Xr ports 7
.Sh AUTHORS
.An Tobias Kortkamp Aq Mt tobik@FreeBSD.org
