PORTNAME=	arj
PORTVERSION=	3.10.22

IGNORE_PATCHES=	002_no_remove_static_const.patch  \
		doc_refer_robert_k_jung.patch \
		gnu_build_cross.patch \
		gnu_build_fix.patch \
		gnu_build_flags.patch \
		gnu_build_pie.patch \
		gnu_build_strip.patch \
		hurd_no_fcntl_getlk.patch \
		reproducible_help_archive.patch

.include <bsd.port.mk>
